name: Slither Analysis

on:
  push:
    branches:
      - "release/**"
      - "releases/**"
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
      - "chore/**"
      - "test/**"
      - "unit/**"
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Slither
        # TODO: change to official version after it is bug free, ref: https://github.com/crytic/slither-action/issues/49
        uses: crytic/slither-action@dev-git-safe-workspace
        with:
          node-version: 16.16.0 # should match .nvmrc or whatever your project required
          target: "./"
          slither-config: ./slither.config.json
          slither-version: 0.9.2
          solc-version: 0.8.18
          slither-args: --fail-pedantic
